name: build

on:
  push: # any branch push triggers
  workflow_dispatch: # enables manual triggering in GitHub UI

env:
  DOTNET_VERSION: 6.0.x
  BUILD_CONFIGURATION: Release
  PROJECT_PATH: ./Hello.Web         # set this to the directory path of your project
  PUBLISH_PATH: ./myapp
  TESTRESULTS_PATH: ./test-results
  AZURE_WEBAPP_NAME: HelloWeb-test  # set this to your Azure's app name

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build code
        run: |
          dotnet build \
            --configuration $BUILD_CONFIGURATION \
            --no-restore
      - name: Run unit tests
        run: |
          dotnet test \
            --configuration $BUILD_CONFIGURATION \
            --no-build \
            --logger trx \
            --results-directory $TESTRESULTS_PATH
      - name: Store test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ${{ env.TESTRESULTS_PATH }}
        if: ${{ always() }} # ensures test results uploaded even after failure
      - name: Package build
        run: |
          dotnet publish $PROJECT_PATH \
            --configuration $BUILD_CONFIGURATION \
            --no-build \
            --output $PUBLISH_PATH
      - name: Store build artefact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ env.PUBLISH_PATH }}

  deploy-test:
    runs-on: ubuntu-latest
    needs: build
#   environment:
#     name: 'production'
#     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#   if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: ${{ env.PUBLISH_PATH }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret in GitHub with contents of Publish Profile
          package: ${{ env.PUBLISH_PATH }}
